import type {
  Check,
  CommandDoc,
  CourseLevel,
  CourseModule,
  GlossaryEntry,
  Lesson,
  QuizQuestion,
} from "./types";

const lesson = (
  id: string,
  title: string,
  eyebrow: string,
  intro: string,
  points: string[],
  command: string,
  example: string,
  prompt: string,
  checks: Check[],
  hints: [string, string, string],
  success: string,
  xp = 30,
  commandBreakdown: { token: string; meaning: string }[] = [],
): Lesson => ({
  id,
  title,
  eyebrow,
  intro,
  points,
  command,
  example,
  commandBreakdown,
  exercise: { prompt, checks, hints, success, xp },
});

const courseModule = (
  id: string,
  level: number,
  number: number,
  title: string,
  subtitle: string,
  icon: string,
  skills: string[],
  lessons: Lesson[],
): CourseModule => ({
  id,
  level,
  number,
  title,
  subtitle,
  icon,
  skills,
  lessons,
  duration: lessons.length * 7,
});

const question = (
  questionText: string,
  choices: string[],
  answer: number,
  explanation: string,
): QuizQuestion => ({ question: questionText, choices, answer, explanation });

const level1Modules: CourseModule[] = [
  courseModule("l1-linux", 1, 1, "Bienvenue dans Linux", "Comprendre le terrain de jeu", "◉", ["linux", "system"], [
    lesson(
      "l1-linux-uname",
      "Linux, c'est quoi ?",
      "Découverte",
      "Linux est le cœur du système. Une distribution ajoute les logiciels et l'interface nécessaires pour former un système complet.",
      ["Le noyau relie les logiciels au matériel.", "Ubuntu, Debian ou Fedora sont des distributions.", "Ici, tout se passe dans un laboratoire sans danger."],
      "uname",
      "uname",
      "Demande au système quel noyau il utilise.",
      [{ type: "output", includes: "Linux", label: "Le terminal affiche Linux" }],
      ["Il existe une commande qui signifie « nom du système ».", "Elle commence par la lettre u.", "Saisis uname."],
      "Tu viens d'interroger le noyau. Le laboratoire répond Linux, comme une vraie machine.",
      25,
      [{ token: "uname", meaning: "affiche le nom du système" }],
    ),
    lesson(
      "l1-linux-whoami",
      "Qui suis-je ?",
      "Identité",
      "Dans Linux, chaque action est réalisée par un utilisateur. Connaître son identité permet de comprendre ses droits.",
      ["Ton utilisateur d'entraînement s'appelle learner.", "Un administrateur possède davantage de droits.", "On évite de travailler en administrateur sans nécessité."],
      "whoami",
      "whoami",
      "Affiche le nom de l'utilisateur connecté.",
      [{ type: "output", includes: "learner", label: "Le terminal affiche learner" }],
      ["La commande pose littéralement la question « qui suis-je ? ».", "Écris les mots who et am et la lettre i, sans espace.", "Saisis whoami."],
      "Parfait. Tu travailles comme learner, un utilisateur isolé du vrai appareil.",
    ),
  ]),
  courseModule("l1-terminal", 1, 2, "Parler au terminal", "Commande, argument et résultat", ">_", ["terminal", "echo"], [
    lesson(
      "l1-terminal-echo",
      "Faire parler le terminal",
      "Première commande",
      "Une commande demande une action. Les mots placés après elle sont généralement ses arguments.",
      ["echo affiche le texte qu'on lui donne.", "La touche Entrée lance la commande.", "Le résultat apparaît sur la ligne suivante."],
      "echo",
      "echo Bonjour Linux",
      "Fais afficher exactement : Bonjour Linux",
      [{ type: "output", includes: "Bonjour Linux", label: "Le message Bonjour Linux est affiché" }],
      ["Utilise la commande qui répète un texte.", "Commence par echo puis ajoute le message.", "Saisis echo Bonjour Linux."],
      "Excellent. echo est la commande et « Bonjour Linux » est son argument.",
      25,
      [
        { token: "echo", meaning: "commande d'affichage" },
        { token: "Bonjour Linux", meaning: "texte transmis à la commande" },
      ],
    ),
    lesson(
      "l1-terminal-date",
      "Interroger le système",
      "Commande sans argument",
      "Certaines commandes fonctionnent seules. Elles récupèrent directement une information du système.",
      ["date affiche la date et l'heure.", "Une commande peut avoir zéro, un ou plusieurs arguments.", "La sortie est le texte produit par la commande."],
      "date",
      "date",
      "Affiche la date et l'heure du laboratoire.",
      [{ type: "command", pattern: "^date$", label: "La commande date est exécutée" }],
      ["Le nom de la commande est identique à l'information recherchée.", "Elle comporte quatre lettres.", "Saisis date."],
      "Bien joué. Tu sais maintenant exécuter une commande sans argument.",
    ),
  ]),
  courseModule("l1-location", 1, 3, "Se repérer", "Dossier actuel et contenu", "⌖", ["pwd", "ls"], [
    lesson(
      "l1-location-pwd",
      "Où suis-je ?",
      "Navigation",
      "Le terminal travaille toujours depuis un dossier précis, appelé dossier courant.",
      ["pwd signifie print working directory.", "Le chemin commence par /, la racine du système.", "Ton dossier personnel est /home/learner."],
      "pwd",
      "pwd",
      "Affiche le chemin complet du dossier actuel.",
      [{ type: "output", includes: "/home/learner", label: "Le chemin /home/learner est affiché" }],
      ["Cherche la commande qui affiche le working directory.", "Son nom contient trois lettres.", "Saisis pwd."],
      "Tu es dans ton dossier personnel : /home/learner.",
    ),
    lesson(
      "l1-location-ls",
      "Voir ce qui m'entoure",
      "Exploration",
      "La commande ls affiche les fichiers et dossiers présents à l'emplacement actuel.",
      ["Les noms terminés par / sont des dossiers dans notre laboratoire.", "ls -a montre aussi les éléments cachés.", "ls -l donne davantage de détails."],
      "ls",
      "ls",
      "Affiche le contenu du dossier actuel.",
      [{ type: "command", pattern: "^ls(?:\\s+\\.)?$", label: "Le contenu est listé avec ls" }],
      ["Cette commande signifie list.", "Elle ne comporte que deux lettres.", "Saisis ls."],
      "Tu viens de regarder le contenu de ton dossier sans rien modifier.",
    ),
  ]),
  courseModule("l1-help", 1, 4, "Ne jamais rester bloqué", "Aide et historique", "?", ["help", "history"], [
    lesson(
      "l1-help-command",
      "Demander de l'aide",
      "Autonomie",
      "Même les professionnels consultent l'aide. Le but n'est pas de tout mémoriser, mais de savoir retrouver l'information.",
      ["help nom_commande affiche une fiche simple.", "Sur un vrai Linux, man ouvre le manuel complet.", "L'option --help est aussi très fréquente."],
      "help",
      "help ls",
      "Affiche l'aide de la commande ls.",
      [{ type: "command", pattern: "^(?:help\\s+ls|man\\s+ls|ls\\s+--help)$", label: "L'aide de ls est consultée" }],
      ["Utilise help suivi du nom de la commande.", "La commande concernée est ls.", "Saisis help ls."],
      "Bonne habitude : demander de l'aide est une compétence, pas un échec.",
    ),
    lesson(
      "l1-help-history",
      "Retrouver mes commandes",
      "Mémoire du terminal",
      "Le shell conserve les commandes déjà exécutées pendant la session.",
      ["history affiche la liste des commandes.", "Les flèches haut et bas les rappellent rapidement.", "L'historique de l'application est uniquement pédagogique."],
      "history",
      "history",
      "Affiche les commandes exécutées depuis le début de la session.",
      [{ type: "command", pattern: "^history$", label: "L'historique est affiché" }],
      ["La commande porte le nom anglais de l'historique.", "Elle commence par hist.", "Saisis history."],
      "Tu sais maintenant retrouver une ancienne commande au lieu de la retaper.",
    ),
  ]),
  courseModule("l1-mission", 1, 5, "Première mission", "Explorer sans assistance", "★", ["cd", "ls", "pwd"], [
    lesson(
      "l1-mission-documents",
      "Entrer dans Documents",
      "Mission guidée",
      "Tu vas changer de dossier. cd signifie change directory.",
      ["Le nom du dossier vient après cd.", "Le prompt change lorsque tu te déplaces.", "pwd permet toujours de vérifier ta position."],
      "cd",
      "cd Documents",
      "Entre dans le dossier Documents.",
      [{ type: "cwd", path: "/home/learner/Documents", label: "Le dossier courant est Documents" }],
      ["Utilise la commande de changement de dossier.", "Ajoute Documents après cd.", "Saisis cd Documents."],
      "Tu viens d'effectuer ton premier déplacement dans l'arborescence.",
    ),
    lesson(
      "l1-mission-inspect",
      "Inspecter la destination",
      "Mission autonome",
      "Une fois arrivé, vérifie toujours ta position puis observe le contenu.",
      ["pwd confirme l'emplacement.", "ls affiche les éléments présents.", "Tu peux exécuter plusieurs commandes l'une après l'autre."],
      "ls",
      "ls",
      "Depuis Documents, affiche les fichiers présents.",
      [
        { type: "cwd", path: "/home/learner/Documents", label: "Tu restes dans Documents" },
        { type: "command", pattern: "^ls(?:\\s+\\.)?$", label: "Le contenu de Documents est listé" },
      ],
      ["Vérifie que le prompt termine par Documents.", "Utilise la commande apprise pour lister.", "Saisis ls."],
      "Mission accomplie. Tu sais interroger le système, te repérer et explorer.",
      50,
    ),
  ]),
];

const level2Modules: CourseModule[] = [
  courseModule("l2-paths", 2, 6, "Chemins Linux", "Absolus, relatifs et raccourcis", "↗", ["paths", "cd"], [
    lesson(
      "l2-paths-absolute",
      "Utiliser un chemin absolu",
      "Système de fichiers",
      "Un chemin absolu part toujours de la racine /. Il désigne un emplacement sans dépendre du dossier actuel.",
      ["/home/learner/Projets est un chemin absolu.", "Le caractère / sépare les dossiers.", "Un chemin exact évite les ambiguïtés."],
      "cd",
      "cd /home/learner/Projets",
      "Va dans Projets en utilisant son chemin absolu.",
      [{ type: "cwd", path: "/home/learner/Projets", label: "Le dossier courant est /home/learner/Projets" }],
      ["Commence le chemin par /.", "Le dossier se trouve dans /home/learner.", "Saisis cd /home/learner/Projets."],
      "Un chemin absolu fonctionne depuis n'importe quel dossier.",
    ),
    lesson(
      "l2-paths-parent",
      "Remonter au dossier parent",
      "Chemin relatif",
      "Deux points, .., représentent le dossier parent. Un point, ., représente le dossier actuel.",
      ["cd .. remonte d'un niveau.", "cd ~ retourne au dossier personnel.", "Les chemins relatifs partent de ta position actuelle."],
      "cd",
      "cd ..",
      "Remonte de Projets vers le dossier personnel avec le raccourci parent.",
      [{ type: "cwd", path: "/home/learner", label: "Tu es revenu dans /home/learner" }],
      ["Le parent est représenté par deux points.", "Place ces deux points après cd.", "Saisis cd ..."],
      "Tu sais maintenant remonter dans l'arborescence sans retaper le chemin complet.",
    ),
  ]),
  courseModule("l2-create", 2, 7, "Créer et organiser", "Dossiers et fichiers", "+", ["mkdir", "touch"], [
    lesson(
      "l2-create-directory",
      "Créer un dossier",
      "Organisation",
      "mkdir crée un nouveau dossier. Un nom simple et clair rend ton travail plus facile à retrouver.",
      ["mkdir signifie make directory.", "L'option -p peut créer plusieurs niveaux.", "Linux distingue les majuscules des minuscules."],
      "mkdir",
      "mkdir atelier",
      "Crée un dossier nommé atelier dans ton dossier personnel.",
      [{ type: "fileExists", path: "/home/learner/atelier", label: "Le dossier atelier existe" }],
      ["Utilise la commande make directory.", "Ajoute le nom atelier.", "Saisis mkdir atelier."],
      "Le dossier atelier est maintenant présent dans ton espace virtuel.",
    ),
    lesson(
      "l2-create-file",
      "Créer un fichier vide",
      "Fichiers",
      "touch crée un fichier vide s'il n'existe pas. S'il existe déjà, il met à jour sa date de modification.",
      ["On peut préciser un chemin complet.", "L'extension .txt indique un fichier texte.", "La commande ne remplit pas le fichier."],
      "touch",
      "touch atelier/readme.txt",
      "Crée le fichier readme.txt à l'intérieur du dossier atelier.",
      [{ type: "fileExists", path: "/home/learner/atelier/readme.txt", label: "atelier/readme.txt existe" }],
      ["Utilise touch.", "Précise le dossier puis le fichier avec /.", "Saisis touch atelier/readme.txt."],
      "Tu viens de créer un fichier dans un sous-dossier grâce à un chemin relatif.",
    ),
  ]),
  courseModule("l2-text", 2, 8, "Lire et écrire", "Contenu des fichiers", "≡", ["cat", "redirection"], [
    lesson(
      "l2-text-cat",
      "Lire un fichier",
      "Texte",
      "cat affiche rapidement le contenu d'un fichier texte dans le terminal.",
      ["cat convient aux fichiers courts.", "less est préférable pour un très long fichier.", "Le nom du fichier est un argument."],
      "cat",
      "cat notes.txt",
      "Affiche le contenu du fichier notes.txt.",
      [{ type: "output", includes: "commande", label: "Le contenu de notes.txt est affiché" }],
      ["La commande commence par ca.", "Ajoute le nom du fichier après cat.", "Saisis cat notes.txt."],
      "Tu as lu un fichier sans le modifier.",
    ),
    lesson(
      "l2-text-write",
      "Écrire avec une redirection",
      "Sortie",
      "Le symbole > envoie la sortie d'une commande dans un fichier au lieu de l'afficher.",
      ["> remplace le contenu existant.", ">> ajoute à la fin.", "La redirection est traitée par le shell."],
      ">",
      "echo Linux en pratique > journal.txt",
      "Crée journal.txt contenant les mots Linux en pratique.",
      [
        { type: "fileExists", path: "/home/learner/journal.txt", label: "journal.txt existe" },
        { type: "fileContent", path: "/home/learner/journal.txt", includes: "Linux en pratique", label: "Le texte est enregistré" },
      ],
      ["Fais produire le texte avec echo.", "Place > avant le nom du fichier.", "Saisis echo Linux en pratique > journal.txt."],
      "La sortie de echo a été enregistrée dans journal.txt.",
      35,
    ),
  ]),
  courseModule("l2-copy", 2, 9, "Copier et déplacer", "Maîtriser ses fichiers", "⇄", ["cp", "mv"], [
    lesson(
      "l2-copy-cp",
      "Copier sans perdre l'original",
      "Fichiers",
      "cp reçoit une source puis une destination. Le fichier d'origine reste en place.",
      ["L'ordre est toujours source puis destination.", "La destination peut être un dossier.", "cp -r copie un dossier et son contenu."],
      "cp",
      "cp notes.txt Documents/notes-copy.txt",
      "Copie notes.txt vers Documents sous le nom notes-copy.txt.",
      [{ type: "fileExists", path: "/home/learner/Documents/notes-copy.txt", label: "La copie existe dans Documents" }],
      ["Utilise cp avec deux chemins.", "La source est notes.txt.", "Saisis cp notes.txt Documents/notes-copy.txt."],
      "L'original et sa copie existent maintenant tous les deux.",
    ),
    lesson(
      "l2-copy-mv",
      "Déplacer ou renommer",
      "Fichiers",
      "mv déplace un élément. Lorsque la destination est dans le même dossier, il sert aussi à renommer.",
      ["La source disparaît de son ancien emplacement.", "Le contenu reste intact.", "Vérifie toujours les deux chemins avant Entrée."],
      "mv",
      "mkdir -p atelier\nmv journal.txt atelier/journal.txt",
      "Crée le dossier atelier s'il manque, puis déplace journal.txt à l'intérieur.",
      [
        { type: "fileExists", path: "/home/learner/atelier/journal.txt", label: "journal.txt est dans atelier" },
        { type: "fileMissing", path: "/home/learner/journal.txt", label: "L'ancien emplacement est vide" },
      ],
      ["Vérifie d'abord que le dossier atelier existe.", "Crée-le avec mkdir -p atelier, puis utilise mv.", "Saisis mkdir -p atelier, puis mv journal.txt atelier/journal.txt."],
      "Le fichier a changé d'emplacement sans perdre son contenu.",
    ),
  ]),
  courseModule("l2-clean", 2, 10, "Nettoyer et archiver", "Suppression contrôlée et sauvegarde", "⌫", ["rm", "tar"], [
    lesson(
      "l2-clean-rm",
      "Supprimer prudemment",
      "Sécurité",
      "rm supprime un fichier sans passer par une corbeille. Dans ce laboratoire, tout reste réinitialisable.",
      ["Vérifie pwd et ls avant une suppression.", "L'option -r concerne les dossiers.", "L'option -f force et doit être utilisée avec prudence."],
      "rm",
      "rm temp.txt",
      "Supprime le fichier temporaire temp.txt.",
      [{ type: "fileMissing", path: "/home/learner/temp.txt", label: "temp.txt a été supprimé" }],
      ["Utilise remove.", "Ne mets aucune option pour ce simple fichier.", "Saisis rm temp.txt."],
      "Le fichier temporaire a disparu. Sur une vraie machine, cette action serait définitive.",
    ),
    lesson(
      "l2-clean-tar",
      "Créer une archive",
      "Sauvegarde",
      "tar regroupe plusieurs fichiers. Avec -czf, il crée une archive compressée gzip.",
      ["c signifie créer.", "z active gzip.", "f indique que le nom de l'archive suit.", "Le dernier argument est le dossier à archiver."],
      "tar",
      "tar -czf documents.tar.gz Documents",
      "Crée l'archive documents.tar.gz à partir du dossier Documents.",
      [{ type: "fileExists", path: "/home/learner/documents.tar.gz", label: "L'archive documents.tar.gz existe" }],
      ["Utilise tar avec les options -czf.", "Le nom de l'archive vient avant le dossier source.", "Saisis tar -czf documents.tar.gz Documents."],
      "Tu as créé une archive compressée prête à être sauvegardée ou transférée.",
      45,
    ),
  ]),
];

const level3Modules: CourseModule[] = [
  courseModule("l3-permissions", 3, 11, "Permissions", "Lire, écrire, exécuter", "◆", ["chmod", "stat"], [
    lesson(
      "l3-permissions-stat",
      "Examiner les droits",
      "Administration",
      "Chaque fichier possède des droits pour son propriétaire, son groupe et les autres utilisateurs.",
      ["r signifie lecture, w écriture et x exécution.", "stat donne les informations détaillées.", "Un secret ne doit pas être lisible par tout le monde."],
      "stat",
      "stat secrets.txt",
      "Affiche les informations et les permissions de secrets.txt.",
      [{ type: "command", pattern: "^stat\\s+secrets\\.txt$", label: "Les permissions de secrets.txt sont inspectées" }],
      ["Utilise la commande de statistiques d'un fichier.", "Ajoute secrets.txt après stat.", "Saisis stat secrets.txt."],
      "Tu as vérifié les droits avant de les modifier : c'est la bonne méthode.",
    ),
    lesson(
      "l3-permissions-chmod",
      "Protéger un secret",
      "Administration",
      "chmod modifie les permissions. Le mode 600 autorise uniquement le propriétaire à lire et écrire.",
      ["6 correspond à lecture + écriture.", "0 retire tous les droits.", "600 signifie rw-------."],
      "chmod",
      "chmod 600 secrets.txt",
      "Configure secrets.txt avec les permissions 600.",
      [{ type: "permission", path: "/home/learner/secrets.txt", mode: "600", label: "secrets.txt possède le mode 600" }],
      ["Utilise chmod.", "Le mode attendu est 600.", "Saisis chmod 600 secrets.txt."],
      "Le fichier est maintenant accessible uniquement par son propriétaire.",
      40,
    ),
  ]),
  courseModule("l3-users", 3, 12, "Utilisateurs et groupes", "Comprendre les identités", "♙", ["id", "groups"], [
    lesson(
      "l3-users-id",
      "Lire son identité complète",
      "Comptes",
      "La commande id affiche l'identifiant numérique de l'utilisateur et les groupes auxquels il appartient.",
      ["L'UID identifie l'utilisateur.", "Le GID identifie le groupe principal.", "Les groupes accordent des droits collectifs."],
      "id",
      "id",
      "Affiche l'UID, le GID et les groupes de l'utilisateur actuel.",
      [{ type: "output", includes: "uid=1000", label: "L'UID de learner est affiché" }],
      ["La commande porte le nom de l'identifiant.", "Elle comporte deux lettres.", "Saisis id."],
      "learner possède l'UID 1000 et appartient aux groupes learner et developers.",
    ),
    lesson(
      "l3-users-groups",
      "Lister ses groupes",
      "Comptes",
      "groups affiche uniquement les groupes d'un utilisateur, de façon plus lisible que id.",
      ["Un utilisateur peut appartenir à plusieurs groupes.", "Les permissions de groupe facilitent le travail en équipe.", "sudo est réservé aux actions d'administration."],
      "groups",
      "groups",
      "Affiche les groupes auxquels appartient learner.",
      [{ type: "output", includes: "developers", label: "Le groupe developers est affiché" }],
      ["Le nom de la commande est le pluriel anglais de groupe.", "Elle commence par group.", "Saisis groups."],
      "Tu sais maintenant vérifier rapidement les groupes d'un compte.",
    ),
  ]),
  courseModule("l3-packages", 3, 13, "Installer des logiciels", "Paquets et dépôts", "⬡", ["apt", "packages"], [
    lesson(
      "l3-packages-update",
      "Actualiser le catalogue",
      "Logiciels",
      "Sur Debian et Ubuntu, apt gère les paquets. update récupère la liste actuelle des logiciels disponibles.",
      ["update n'installe pas les mises à jour.", "upgrade applique les mises à jour disponibles.", "Un dépôt est une source de paquets vérifiés."],
      "apt",
      "sudo apt update",
      "Actualise la liste des paquets disponibles.",
      [{ type: "command", pattern: "^(?:sudo\\s+)?apt\\s+update$", label: "Le catalogue des paquets est actualisé" }],
      ["Utilise apt avec l'action update.", "Une action système réelle demanderait souvent sudo.", "Saisis sudo apt update."],
      "Le catalogue du laboratoire est à jour. Aucun vrai téléchargement n'a été effectué.",
      35,
    ),
    lesson(
      "l3-packages-install",
      "Installer un paquet",
      "Logiciels",
      "apt install ajoute un logiciel et ses dépendances depuis les dépôts configurés.",
      ["Le nom du paquet vient après install.", "L'option -y répond automatiquement oui.", "On vérifie toujours la source d'un paquet."],
      "apt",
      "sudo apt install tree",
      "Installe le paquet tree dans le laboratoire.",
      [{ type: "package", name: "tree", label: "Le paquet tree est installé" }],
      ["Utilise apt install.", "Le paquet demandé s'appelle tree.", "Saisis sudo apt install tree."],
      "tree est maintenant installé dans la simulation.",
      45,
    ),
  ]),
  courseModule("l3-processes", 3, 14, "Processus", "Observer et intervenir", "◌", ["ps", "kill"], [
    lesson(
      "l3-processes-ps",
      "Voir les programmes actifs",
      "Processus",
      "Chaque programme en cours possède un processus et un numéro PID.",
      ["ps affiche les processus.", "ps aux donne une vue détaillée.", "top actualise la liste en temps réel sur un vrai système."],
      "ps",
      "ps aux",
      "Affiche la liste détaillée des processus du laboratoire.",
      [{ type: "output", includes: "4242", label: "Le processus bloqué PID 4242 est visible" }],
      ["Utilise ps.", "Ajoute les lettres a, u et x.", "Saisis ps aux."],
      "Tu as repéré worker-bloque avec le PID 4242.",
    ),
    lesson(
      "l3-processes-kill",
      "Arrêter le bon processus",
      "Diagnostic",
      "kill envoie un signal à un processus. Par défaut, il demande un arrêt propre avec SIGTERM.",
      ["On cible un PID précis.", "kill -9 force l'arrêt et reste un dernier recours.", "Il faut vérifier le résultat avec ps."],
      "kill",
      "kill 4242",
      "Arrête proprement le processus bloqué dont le PID est 4242.",
      [{ type: "processKilled", pid: 4242, label: "Le processus 4242 est arrêté" }],
      ["Utilise kill sans option pour un arrêt propre.", "Le PID repéré est 4242.", "Saisis kill 4242."],
      "Le processus bloqué a reçu un signal d'arrêt propre.",
      45,
    ),
  ]),
  courseModule("l3-environment", 3, 15, "Environnement", "Variables et PATH", "$", ["env", "export"], [
    lesson(
      "l3-environment-env",
      "Voir les variables",
      "Shell",
      "Les variables d'environnement transmettent des réglages aux programmes.",
      ["HOME désigne le dossier personnel.", "USER contient le nom du compte.", "PATH indique où rechercher les commandes."],
      "env",
      "env",
      "Affiche toutes les variables d'environnement du laboratoire.",
      [{ type: "output", includes: "PATH=", label: "La variable PATH est affichée" }],
      ["Utilise le nom abrégé d'environnement.", "La commande contient trois lettres.", "Saisis env."],
      "Tu peux maintenant examiner le contexte transmis aux programmes.",
    ),
    lesson(
      "l3-environment-export",
      "Créer une variable",
      "Shell",
      "export crée une variable disponible pour les commandes lancées depuis le shell.",
      ["La syntaxe est NOM=valeur sans espace autour de =.", "Les noms sont souvent en majuscules.", "La valeur peut ensuite être lue avec $NOM."],
      "export",
      "export PROJECT=CR3ATIX",
      "Crée la variable PROJECT avec la valeur CR3ATIX.",
      [{ type: "env", name: "PROJECT", value: "CR3ATIX", label: "PROJECT vaut CR3ATIX" }],
      ["Utilise export.", "Écris PROJECT=CR3ATIX sans espaces.", "Saisis export PROJECT=CR3ATIX."],
      "La variable PROJECT est active pour toute la session du laboratoire.",
      40,
    ),
  ]),
  courseModule("l3-search", 3, 16, "Rechercher", "Fichiers et contenu", "⌕", ["find", "grep"], [
    lesson(
      "l3-search-find",
      "Retrouver un fichier",
      "Recherche",
      "find parcourt une arborescence pour retrouver des fichiers selon leur nom ou d'autres critères.",
      ["Le premier argument est le point de départ.", "-name filtre le nom.", "Les guillemets protègent le caractère * du shell."],
      "find",
      "find . -name \"*.log\"",
      "Retrouve tous les fichiers dont le nom se termine par .log.",
      [{ type: "output", includes: "logs/app.log", label: "Le fichier logs/app.log est retrouvé" }],
      ["Utilise find depuis le dossier actuel représenté par .", "Ajoute -name puis le motif *.log.", "Saisis find . -name \"*.log\"."],
      "Tu as retrouvé un fichier sans connaître son dossier exact.",
    ),
    lesson(
      "l3-search-grep",
      "Chercher dans un fichier",
      "Recherche",
      "grep sélectionne les lignes contenant un texte ou un motif.",
      ["Le motif vient avant le fichier.", "-i ignore la casse.", "-n ajoute le numéro de ligne."],
      "grep",
      "grep ERROR logs/app.log",
      "Affiche uniquement les lignes contenant ERROR dans logs/app.log.",
      [{ type: "output", includes: "ERROR", label: "Les lignes d'erreur sont affichées" }],
      ["Utilise grep.", "Le motif recherché est ERROR.", "Saisis grep ERROR logs/app.log."],
      "Tu sais maintenant isoler les lignes importantes dans un fichier de log.",
      40,
    ),
  ]),
  courseModule("l3-pipes", 3, 17, "Pipes et filtres", "Combiner les commandes", "|", ["pipe", "wc", "sort", "uniq"], [
    lesson(
      "l3-pipes-count",
      "Compter les erreurs",
      "Composition",
      "Le pipe | transmet la sortie de la commande de gauche à l'entrée de celle de droite.",
      ["Chaque commande réalise une tâche simple.", "wc -l compte les lignes.", "Les commandes peuvent être assemblées sans fichier intermédiaire."],
      "|",
      "grep ERROR logs/app.log | wc -l",
      "Compte le nombre de lignes ERROR dans logs/app.log avec un pipe.",
      [
        { type: "command", pattern: "^grep\\s+ERROR\\s+logs/app\\.log\\s*\\|\\s*wc\\s+-l$", label: "grep est relié à wc -l" },
        { type: "output", includes: "2", label: "Le résultat indique 2 erreurs" },
      ],
      ["Commence par grep ERROR logs/app.log.", "Envoie son résultat vers wc -l avec |.", "Saisis grep ERROR logs/app.log | wc -l."],
      "Tu viens de construire une petite chaîne de traitement Linux.",
      50,
    ),
    lesson(
      "l3-pipes-unique",
      "Trier puis dédupliquer",
      "Composition",
      "sort trie des lignes et uniq supprime les doublons voisins. On les utilise donc souvent ensemble.",
      ["cat peut fournir le contenu initial.", "sort place les doublons côte à côte.", "uniq reçoit ensuite le résultat par un pipe."],
      "|",
      "sort users.txt | uniq",
      "Affiche la liste triée des utilisateurs sans doublon.",
      [{ type: "command", pattern: "^sort\\s+users\\.txt\\s*\\|\\s*uniq$", label: "sort et uniq sont correctement combinés" }],
      ["Trie d'abord users.txt avec sort.", "Ajoute un pipe vers uniq.", "Saisis sort users.txt | uniq."],
      "Le résultat contient maintenant une seule occurrence de chaque utilisateur.",
      50,
    ),
  ]),
];

const level4Modules: CourseModule[] = [
  courseModule("l4-bash", 4, 18, "Bash avancé", "Variables et codes de retour", "{}", ["bash", "variables"], [
    lesson(
      "l4-bash-variable",
      "Lire une variable",
      "Bash",
      "Le caractère $ demande au shell de remplacer le nom d'une variable par sa valeur.",
      ["$USER devient learner.", "Les guillemets doubles autorisent l'expansion.", "Les guillemets simples conservent le texte littéral."],
      "echo",
      "echo $PROJECT",
      "Affiche la valeur de la variable PROJECT créée précédemment.",
      [{ type: "output", includes: "CR3ATIX", label: "La valeur CR3ATIX est affichée" }],
      ["Utilise echo.", "Ajoute le caractère $ devant PROJECT.", "Saisis echo $PROJECT."],
      "Bash a remplacé $PROJECT par sa valeur avant d'exécuter echo.",
      40,
    ),
    lesson(
      "l4-bash-exit",
      "Comprendre le code de retour",
      "Bash",
      "Chaque commande renvoie un nombre. Zéro signifie généralement réussite ; une autre valeur signale une erreur.",
      ["$? contient le dernier code de retour.", "Les scripts l'utilisent pour prendre des décisions.", "Il faut le lire juste après la commande concernée."],
      "echo",
      "echo $?",
      "Affiche le code de retour de la dernière commande réussie.",
      [{ type: "output", includes: "0", label: "Le code de retour 0 est affiché" }],
      ["Le code est stocké dans une variable spéciale.", "Cette variable s'écrit $?.", "Saisis echo $?."],
      "Le code 0 confirme que la commande précédente s'est terminée correctement.",
    ),
  ]),
  courseModule("l4-scripts", 4, 19, "Scripts shell", "Automatiser des séquences", "#!", ["bash", "scripts"], [
    lesson(
      "l4-scripts-backup",
      "Lancer un script",
      "Automatisation",
      "Un script regroupe plusieurs commandes dans un fichier réutilisable.",
      ["La première ligne peut contenir un shebang.", "bash fichier.sh exécute le fichier avec Bash.", "Un script doit vérifier les erreurs importantes."],
      "bash",
      "bash scripts/backup.sh",
      "Exécute le script de sauvegarde fourni dans scripts/backup.sh.",
      [{ type: "fileExists", path: "/home/learner/backups/projets.tar.gz", label: "La sauvegarde projets.tar.gz est créée" }],
      ["Utilise bash suivi du chemin du script.", "Le script se trouve dans scripts.", "Saisis bash scripts/backup.sh."],
      "Le script a créé automatiquement une archive dans le dossier backups.",
      55,
    ),
    lesson(
      "l4-scripts-health",
      "Contrôler l'état du système",
      "Automatisation",
      "Un script de diagnostic peut enchaîner plusieurs vérifications et résumer le résultat.",
      ["Une sortie claire aide les opérations.", "Le code de retour permet l'automatisation.", "Les secrets ne doivent jamais être écrits dans les logs."],
      "bash",
      "bash scripts/healthcheck.sh",
      "Lance le contrôle de santé du laboratoire.",
      [{ type: "output", includes: "ALERTE", label: "Le script signale le service webapp" }],
      ["Le script se trouve aussi dans scripts.", "Son nom est healthcheck.sh.", "Saisis bash scripts/healthcheck.sh."],
      "Le diagnostic a repéré que le service webapp nécessite une intervention.",
      55,
    ),
  ]),
  courseModule("l4-ssh", 4, 20, "Connexion distante", "SSH et transfert", "⇥", ["ssh", "scp"], [
    lesson(
      "l4-ssh-connect",
      "Ouvrir une session SSH",
      "Réseau",
      "SSH permet d'administrer une machine distante à travers une connexion chiffrée.",
      ["La forme est utilisateur@serveur.", "Les clés sont préférables aux mots de passe.", "Il faut vérifier l'identité du serveur à la première connexion."],
      "ssh",
      "ssh admin@server-lab",
      "Connecte-toi au serveur d'entraînement server-lab avec le compte admin.",
      [{ type: "ssh", host: "server-lab", label: "La connexion SSH à server-lab est ouverte" }],
      ["Utilise ssh.", "Le compte et le serveur se séparent par @.", "Saisis ssh admin@server-lab."],
      "Connexion simulée ouverte. Aucun serveur extérieur n'a été contacté.",
      50,
    ),
    lesson(
      "l4-ssh-copy",
      "Copier par SSH",
      "Réseau",
      "scp copie un fichier en utilisant SSH. La destination distante contient un deux-points après le serveur.",
      ["La source vient en premier.", "Le chemin distant suit utilisateur@serveur:.", "rsync est souvent plus efficace pour de gros transferts."],
      "scp",
      "scp notes.txt admin@server-lab:/tmp/",
      "Envoie notes.txt dans /tmp/ sur server-lab.",
      [{ type: "command", pattern: "^scp\\s+notes\\.txt\\s+admin@server-lab:/tmp/?$", label: "notes.txt est envoyé vers /tmp/" }],
      ["Utilise scp.", "La destination commence par admin@server-lab:.", "Saisis scp notes.txt admin@server-lab:/tmp/."],
      "Le transfert chiffré a été simulé avec succès.",
      50,
    ),
  ]),
  courseModule("l4-network", 4, 21, "Réseau", "Interfaces, ports et HTTP", "◎", ["ip", "ss", "curl"], [
    lesson(
      "l4-network-ip",
      "Voir les interfaces",
      "Réseau",
      "ip est l'outil moderne pour examiner et configurer le réseau sous Linux.",
      ["ip addr affiche les adresses.", "lo est l'interface de boucle locale.", "Une adresse privée du laboratoire commence ici par 10."],
      "ip",
      "ip addr",
      "Affiche les interfaces et adresses réseau.",
      [{ type: "output", includes: "10.20.0.15", label: "L'adresse du laboratoire est affichée" }],
      ["Utilise la commande ip.", "Ajoute l'action addr.", "Saisis ip addr."],
      "Tu as identifié l'adresse privée 10.20.0.15 du laboratoire.",
    ),
    lesson(
      "l4-network-curl",
      "Tester un service Web",
      "Réseau",
      "curl envoie des requêtes à des services HTTP et affiche leur réponse.",
      ["Il aide à tester une API sans navigateur.", "-I demande uniquement les en-têtes.", "Les codes HTTP indiquent le résultat de la requête."],
      "curl",
      "curl http://web.lab",
      "Interroge le service interne http://web.lab.",
      [{ type: "output", includes: "503", label: "Le service répond avec le code 503" }],
      ["Utilise curl suivi de l'adresse.", "Le service utilise HTTP.", "Saisis curl http://web.lab."],
      "Le code 503 confirme que le service existe mais qu'il est momentanément indisponible.",
      45,
    ),
  ]),
  courseModule("l4-admin", 4, 22, "Administration système", "Disques, logs et services", "▣", ["df", "journalctl", "systemctl"], [
    lesson(
      "l4-admin-disk",
      "Vérifier l'espace disque",
      "Système",
      "df affiche l'espace des systèmes de fichiers. L'option -h utilise des unités lisibles.",
      ["Une partition pleine peut arrêter un service.", "du mesure la taille des dossiers.", "Il faut identifier la cause avant de supprimer."],
      "df",
      "df -h",
      "Affiche l'utilisation des disques avec des unités lisibles.",
      [{ type: "output", includes: "78%", label: "L'utilisation de / est affichée" }],
      ["Utilise df.", "Ajoute l'option human readable.", "Saisis df -h."],
      "La partition principale est utilisée à 78 %, ce qui mérite une surveillance.",
    ),
    lesson(
      "l4-admin-logs",
      "Lire les logs d'un service",
      "Diagnostic",
      "journalctl consulte le journal systemd. -u limite l'affichage à une unité précise.",
      ["Commence par lire avant de redémarrer.", "Les heures permettent de reconstituer l'incident.", "Un message d'erreur doit être relié à sa cause."],
      "journalctl",
      "journalctl -u webapp",
      "Affiche les journaux du service webapp.",
      [{ type: "output", includes: "configuration invalide", label: "La cause de l'arrêt est visible" }],
      ["Utilise journalctl.", "L'option d'unité est -u.", "Saisis journalctl -u webapp."],
      "Tu as trouvé la cause : une configuration invalide a arrêté webapp.",
      55,
    ),
  ]),
];

const level5Modules: CourseModule[] = [
  courseModule("l5-security", 5, 23, "Sécurisation", "Clés, droits et pare-feu", "⬢", ["security", "chmod", "ufw"], [
    lesson(
      "l5-security-key",
      "Protéger une clé privée",
      "Durcissement",
      "Une clé SSH privée ne doit être accessible que par son propriétaire. SSH refuse souvent une clé trop ouverte.",
      ["Le mode recommandé est 600.", "La clé publique peut être partagée, jamais la clé privée.", "Une fuite impose la révocation de la clé."],
      "chmod",
      "chmod 600 .ssh/id_ed25519",
      "Corrige les permissions de la clé privée .ssh/id_ed25519.",
      [{ type: "permission", path: "/home/learner/.ssh/id_ed25519", mode: "600", label: "La clé privée possède le mode 600" }],
      ["Utilise chmod.", "Le mode attendu est 600.", "Saisis chmod 600 .ssh/id_ed25519."],
      "La clé privée n'est désormais lisible que par learner.",
      60,
    ),
    lesson(
      "l5-security-firewall",
      "Contrôler le pare-feu",
      "Durcissement",
      "Un pare-feu limite les connexions entrantes et sortantes selon une politique explicite.",
      ["On autorise uniquement les services nécessaires.", "SSH ne doit pas être exposé sans protection.", "ufw simplifie la gestion de netfilter sur Ubuntu."],
      "ufw",
      "sudo ufw status",
      "Affiche l'état et les règles du pare-feu.",
      [{ type: "output", includes: "Status: active", label: "Le pare-feu est actif" }],
      ["Utilise ufw avec l'action status.", "Cette lecture administrative peut être précédée de sudo.", "Saisis sudo ufw status."],
      "Le pare-feu est actif et seuls SSH et HTTP sont autorisés dans le laboratoire.",
      50,
    ),
  ]),
  courseModule("l5-git", 5, 24, "Git professionnel", "État, historique et changements", "⌘", ["git", "versioning"], [
    lesson(
      "l5-git-status",
      "Inspecter avant d'agir",
      "Développement",
      "git status est le point de départ : il montre la branche et les changements non enregistrés.",
      ["Un dépôt conserve l'historique du projet.", "Un commit représente un changement cohérent.", "On ne versionne jamais les secrets."],
      "git",
      "git status",
      "Affiche l'état du dépôt de démonstration.",
      [{ type: "output", includes: "modified: config.yml", label: "Le fichier modifié est identifié" }],
      ["Utilise git.", "L'action demandée est status.", "Saisis git status."],
      "Tu as identifié une modification non enregistrée dans config.yml.",
    ),
    lesson(
      "l5-git-log",
      "Comprendre l'historique",
      "Développement",
      "git log affiche les commits, leurs auteurs et leurs messages.",
      ["--oneline produit une vue compacte.", "Un bon message explique l'intention.", "L'historique aide à diagnostiquer une régression."],
      "git",
      "git log --oneline",
      "Affiche l'historique Git sous forme compacte.",
      [{ type: "output", includes: "fix: sécurise", label: "Le dernier correctif est visible" }],
      ["Utilise git log.", "Ajoute l'option de présentation sur une ligne.", "Saisis git log --oneline."],
      "L'historique montre clairement les derniers changements du projet.",
      45,
    ),
  ]),
  courseModule("l5-docker", 5, 25, "Docker et conteneurs", "Services isolés et reproductibles", "▤", ["docker", "containers"], [
    lesson(
      "l5-docker-ps",
      "Observer les conteneurs",
      "Conteneurs",
      "docker ps affiche les conteneurs actifs, leurs images, ports et états.",
      ["Une image est le modèle immuable.", "Un conteneur est une instance en cours.", "Les données persistantes vivent dans des volumes."],
      "docker",
      "docker ps",
      "Affiche les conteneurs actuellement actifs.",
      [{ type: "output", includes: "api", label: "Le conteneur api est visible" }],
      ["Utilise docker.", "L'action de liste des processus est ps.", "Saisis docker ps."],
      "Le conteneur api est présent mais son état signale un problème.",
    ),
    lesson(
      "l5-docker-compose",
      "Voir une application Compose",
      "Conteneurs",
      "Docker Compose décrit plusieurs services dans un fichier commun et les gère comme une application.",
      ["compose ps liste les services.", "compose logs consulte leurs sorties.", "Un healthcheck indique si un service répond correctement."],
      "docker",
      "docker compose ps",
      "Affiche l'état des services de l'application Compose.",
      [{ type: "output", includes: "unhealthy", label: "Le service api est identifié comme unhealthy" }],
      ["Commence par docker compose.", "Ajoute l'action ps.", "Saisis docker compose ps."],
      "Tu as isolé le service api comme source probable de l'incident.",
      50,
    ),
  ]),
  courseModule("l5-diagnostic", 5, 26, "Diagnostic professionnel", "Prouver avant de corriger", "△", ["logs", "services", "docker"], [
    lesson(
      "l5-diagnostic-service",
      "Rétablir webapp",
      "Incident",
      "Après avoir lu les logs et corrigé la cause, un redémarrage contrôlé permet de remettre le service en ligne.",
      ["status vérifie l'état actuel.", "restart relance le service.", "Il faut ensuite vérifier la réponse applicative."],
      "systemctl",
      "sudo systemctl restart webapp",
      "Redémarre le service webapp.",
      [{ type: "service", name: "webapp", status: "active", label: "Le service webapp est actif" }],
      ["Utilise systemctl.", "L'action attendue est restart.", "Saisis sudo systemctl restart webapp."],
      "webapp est repassé à l'état active. La prochaine étape serait un test HTTP.",
      65,
    ),
    lesson(
      "l5-diagnostic-container",
      "Récupérer le service API",
      "Incident",
      "Un redémarrage peut restaurer un conteneur bloqué, mais il faut toujours surveiller son état ensuite.",
      ["docker restart cible un nom précis.", "Un problème récurrent exige une correction de l'image ou de la configuration.", "Les logs doivent être conservés avant destruction."],
      "docker",
      "docker restart api",
      "Redémarre le conteneur api défaillant.",
      [{ type: "docker", container: "api", status: "running", label: "Le conteneur api fonctionne" }],
      ["Utilise docker restart.", "Le conteneur s'appelle api.", "Saisis docker restart api."],
      "Le conteneur api fonctionne de nouveau. Tu as rétabli les deux services critiques.",
      65,
    ),
  ]),
  courseModule("l5-capstone", 5, 27, "Mission finale", "Administrer, sécuriser et vérifier", "★", ["incident", "security", "verification"], [
    lesson(
      "l5-capstone-repair",
      "Incident CR3@TIX-01",
      "Capstone",
      "Le serveur présente trois problèmes : une clé privée trop ouverte, webapp arrêté et le conteneur api défaillant. Répare l'ensemble sans solution immédiate.",
      ["Observe les états avant d'agir.", "Corrige chaque cause avec la commande adaptée.", "Relance les commandes d'inspection pour vérifier."],
      "diagnostic",
      "chmod 600 .ssh/id_ed25519\nsudo systemctl restart webapp\ndocker restart api",
      "Sécurise la clé SSH, active webapp et remets api en fonctionnement. Plusieurs commandes sont nécessaires.",
      [
        { type: "permission", path: "/home/learner/.ssh/id_ed25519", mode: "600", label: "Clé SSH sécurisée" },
        { type: "service", name: "webapp", status: "active", label: "Service webapp actif" },
        { type: "docker", container: "api", status: "running", label: "Conteneur api fonctionnel" },
      ],
      ["Commence par contrôler la clé, le service et le conteneur.", "Les trois outils nécessaires sont chmod, systemctl et docker.", "Utilise chmod 600, systemctl restart et docker restart sur les bonnes cibles."],
      "Les trois contrôles sont au vert. L'incident technique est résolu.",
      120,
    ),
    lesson(
      "l5-capstone-verify",
      "Vérifier le rétablissement",
      "Capstone",
      "Une intervention n'est terminée que lorsque le service rendu est vérifié de bout en bout.",
      ["Le processus peut fonctionner sans que l'application réponde.", "curl vérifie le point de vue du client.", "Le rapport doit préciser cause, action et résultat."],
      "curl",
      "curl http://web.lab",
      "Vérifie que le service Web répond maintenant correctement.",
      [{ type: "output", includes: "200 OK", label: "Le service répond HTTP 200 OK" }],
      ["Teste l'URL utilisée pendant le diagnostic réseau.", "Utilise curl sur web.lab.", "Saisis curl http://web.lab."],
      "Mission finale accomplie : observation, correction et vérification ont été menées jusqu'au bout.",
      150,
    ),
  ]),
];

export const COURSE_LEVELS: CourseLevel[] = [
  {
    id: 1,
    title: "Découverte",
    rank: "Explorateur Linux",
    description: "Comprendre Linux, le terminal et les premières commandes.",
    color: "cyan",
    modules: level1Modules,
    exam: [
      question("À quoi sert le noyau Linux ?", ["À relier les logiciels au matériel", "À créer des documents", "À remplacer le clavier", "À afficher uniquement le bureau"], 0, "Le noyau gère les ressources et sert d'intermédiaire avec le matériel."),
      question("Quelle commande affiche le dossier actuel ?", ["ls", "pwd", "whoami", "echo"], 1, "pwd signifie print working directory."),
      question("Quelle commande liste le contenu d'un dossier ?", ["cd", "date", "ls", "clear"], 2, "ls vient de list."),
      question("Que représente /home/learner ?", ["Une commande", "Un chemin", "Une option", "Un mot de passe"], 1, "Il s'agit du chemin absolu du dossier personnel."),
      question("Que faut-il faire avant de mémoriser toutes les options ?", ["Éviter le terminal", "Consulter l'aide", "Devenir administrateur", "Réinstaller Linux"], 1, "Savoir consulter l'aide est une compétence essentielle."),
    ],
  },
  {
    id: 2,
    title: "Bases",
    rank: "Opérateur Terminal",
    description: "Naviguer, créer, lire, copier, déplacer et archiver.",
    color: "blue",
    modules: level2Modules,
    exam: [
      question("Quel symbole désigne le dossier parent ?", [".", "..", "~", "/"], 1, "Deux points représentent le parent."),
      question("Quelle commande crée un dossier ?", ["touch", "mkdir", "cp", "cat"], 1, "mkdir signifie make directory."),
      question("Que fait > dans echo test > fichier.txt ?", ["Il supprime le fichier", "Il envoie la sortie dans le fichier", "Il lit le fichier", "Il change de dossier"], 1, "La redirection > écrit la sortie dans le fichier."),
      question("Dans cp source destination, quel argument vient en premier ?", ["La destination", "La source", "L'utilisateur", "Le dossier actuel"], 1, "cp attend d'abord la source."),
      question("Pourquoi rm demande-t-il de la prudence ?", ["Il est toujours lent", "Il modifie le réseau", "Il ne passe pas par une corbeille", "Il change les permissions"], 2, "Une suppression rm est normalement immédiate."),
    ],
  },
  {
    id: 3,
    title: "Intermédiaire",
    rank: "Utilisateur confirmé",
    description: "Permissions, processus, paquets, recherche et pipes.",
    color: "violet",
    modules: level3Modules,
    exam: [
      question("Que signifie le mode 600 ?", ["Tout le monde peut tout faire", "Le propriétaire lit et écrit, les autres n'ont aucun droit", "Lecture seule pour tous", "Exécution uniquement"], 1, "6 vaut lecture + écriture pour le propriétaire."),
      question("Quel identifiant cible kill ?", ["Un UID", "Un PID", "Un GID", "Une IP"], 1, "kill envoie un signal à un processus identifié par son PID."),
      question("Que fait apt update ?", ["Il installe toutes les mises à jour", "Il actualise le catalogue des paquets", "Il supprime les paquets", "Il redémarre Linux"], 1, "update actualise la liste disponible."),
      question("À quoi sert le pipe | ?", ["À supprimer la sortie", "À transmettre la sortie à une autre commande", "À créer un utilisateur", "À chiffrer un fichier"], 1, "Le pipe relie la sortie gauche à l'entrée droite."),
      question("Quelle commande cherche du texte dans un fichier ?", ["find", "grep", "pwd", "chmod"], 1, "grep filtre les lignes selon un motif."),
    ],
  },
  {
    id: 4,
    title: "Avancé",
    rank: "Administrateur Linux",
    description: "Bash, scripts, SSH, réseau, logs et services.",
    color: "pink",
    modules: level4Modules,
    exam: [
      question("Que représente $? dans Bash ?", ["Le dossier personnel", "Le dernier code de retour", "Le PID actuel", "Le nombre de fichiers"], 1, "$? contient le code de sortie de la commande précédente."),
      question("Quel protocole permet une administration distante chiffrée ?", ["FTP", "SSH", "HTTP", "DNS"], 1, "SSH fournit un canal distant chiffré."),
      question("Quelle commande teste facilement une URL depuis le terminal ?", ["curl", "chmod", "df", "tar"], 0, "curl est adapté aux requêtes HTTP."),
      question("Quelle commande consulte le journal systemd ?", ["journalctl", "systemctl", "history", "env"], 0, "journalctl interroge le journal."),
      question("Quelle vérification doit précéder un redémarrage de service ?", ["Changer tous les droits", "Lire son état et ses logs", "Supprimer sa configuration", "Redémarrer la machine"], 1, "On observe et diagnostique avant de modifier."),
    ],
  },
  {
    id: 5,
    title: "Expert / Pro",
    rank: "Ingénieur CR3@TIX",
    description: "Sécurité, Git, Docker et résolution d'incidents.",
    color: "gold",
    modules: level5Modules,
    exam: [
      question("Quel mode convient à une clé SSH privée ?", ["777", "755", "644", "600"], 3, "600 limite lecture et écriture au propriétaire."),
      question("Quelle commande montre les changements Git en attente ?", ["git log", "git status", "git clone", "git push"], 1, "git status est le premier contrôle à effectuer."),
      question("Quelle différence existe entre une image et un conteneur ?", ["Aucune", "L'image est un modèle, le conteneur une instance", "L'image est toujours en ligne", "Le conteneur ne peut pas s'arrêter"], 1, "Une image immuable sert à créer des conteneurs."),
      question("Quand un incident est-il réellement terminé ?", ["Dès que la commande ne renvoie pas d'erreur", "Après redémarrage", "Après vérification du service rendu et documentation", "Après suppression des logs"], 2, "Il faut vérifier de bout en bout puis documenter."),
      question("Quel ordre décrit le mieux un diagnostic professionnel ?", ["Corriger, observer, oublier", "Observer, formuler, tester, corriger, vérifier, documenter", "Redémarrer, supprimer, recommencer", "Installer, désinstaller, redémarrer"], 1, "Une intervention fiable commence par des faits et se termine par une vérification."),
    ],
  },
];

export const ALL_MODULES = COURSE_LEVELS.flatMap((level) => level.modules);
export const ALL_LESSONS = ALL_MODULES.flatMap((courseModule) => courseModule.lessons);

export const COMMAND_DOCS: CommandDoc[] = [
  { name: "pwd", category: "Navigation", level: 1, description: "Affiche le chemin du dossier actuel.", syntax: "pwd", example: "pwd" },
  { name: "ls", category: "Navigation", level: 1, description: "Liste les fichiers et dossiers.", syntax: "ls [options] [chemin]", example: "ls -la" },
  { name: "cd", category: "Navigation", level: 1, description: "Change le dossier actuel.", syntax: "cd [chemin]", example: "cd Documents" },
  { name: "whoami", category: "Système", level: 1, description: "Affiche l'utilisateur connecté.", syntax: "whoami", example: "whoami" },
  { name: "uname", category: "Système", level: 1, description: "Affiche des informations sur le noyau.", syntax: "uname [-a]", example: "uname -a" },
  { name: "echo", category: "Texte", level: 1, description: "Affiche du texte ou une variable.", syntax: "echo [texte]", example: "echo $USER" },
  { name: "history", category: "Terminal", level: 1, description: "Affiche l'historique des commandes.", syntax: "history", example: "history" },
  { name: "mkdir", category: "Fichiers", level: 2, description: "Crée un ou plusieurs dossiers.", syntax: "mkdir [-p] dossier", example: "mkdir -p projet/src" },
  { name: "touch", category: "Fichiers", level: 2, description: "Crée un fichier vide ou actualise sa date.", syntax: "touch fichier", example: "touch notes.txt" },
  { name: "cat", category: "Texte", level: 2, description: "Affiche ou concatène le contenu de fichiers.", syntax: "cat [fichier...]", example: "cat notes.txt" },
  { name: "head", category: "Texte", level: 2, description: "Affiche le début d'un fichier.", syntax: "head [-n nombre] fichier", example: "head -n 5 app.log" },
  { name: "tail", category: "Texte", level: 2, description: "Affiche la fin d'un fichier.", syntax: "tail [-n nombre] fichier", example: "tail -n 20 app.log" },
  { name: "cp", category: "Fichiers", level: 2, description: "Copie un fichier ou un dossier.", syntax: "cp [-r] source destination", example: "cp notes.txt sauvegarde.txt" },
  { name: "mv", category: "Fichiers", level: 2, description: "Déplace ou renomme un élément.", syntax: "mv source destination", example: "mv ancien.txt nouveau.txt" },
  { name: "rm", category: "Fichiers", level: 2, description: "Supprime un fichier ou un dossier.", syntax: "rm [-r] cible", example: "rm brouillon.txt", note: "Pas de corbeille sur un vrai terminal.", danger: true },
  { name: "tar", category: "Archives", level: 2, description: "Crée ou extrait des archives.", syntax: "tar [options] archive sources", example: "tar -czf sauvegarde.tar.gz Documents" },
  { name: "chmod", category: "Permissions", level: 3, description: "Modifie les permissions d'un fichier.", syntax: "chmod mode cible", example: "chmod 600 secret.txt", danger: true },
  { name: "stat", category: "Fichiers", level: 3, description: "Affiche les métadonnées détaillées.", syntax: "stat fichier", example: "stat secret.txt" },
  { name: "id", category: "Utilisateurs", level: 3, description: "Affiche UID, GID et groupes.", syntax: "id [utilisateur]", example: "id" },
  { name: "apt", category: "Paquets", level: 3, description: "Gère les paquets Debian et Ubuntu.", syntax: "apt action [paquet]", example: "sudo apt install tree", danger: true },
  { name: "ps", category: "Processus", level: 3, description: "Affiche les processus actifs.", syntax: "ps [options]", example: "ps aux" },
  { name: "kill", category: "Processus", level: 3, description: "Envoie un signal à un processus.", syntax: "kill [-signal] PID", example: "kill 4242", danger: true },
  { name: "env", category: "Shell", level: 3, description: "Affiche les variables d'environnement.", syntax: "env", example: "env" },
  { name: "export", category: "Shell", level: 3, description: "Crée une variable d'environnement.", syntax: "export NOM=valeur", example: "export PROJECT=CR3ATIX" },
  { name: "find", category: "Recherche", level: 3, description: "Recherche des fichiers dans une arborescence.", syntax: "find chemin critères", example: "find . -name \"*.log\"" },
  { name: "grep", category: "Recherche", level: 3, description: "Sélectionne les lignes correspondant à un motif.", syntax: "grep [options] motif [fichier]", example: "grep -n ERROR app.log" },
  { name: "sort", category: "Texte", level: 3, description: "Trie les lignes de texte.", syntax: "sort [fichier]", example: "sort users.txt" },
  { name: "uniq", category: "Texte", level: 3, description: "Supprime ou compte les doublons voisins.", syntax: "uniq [options]", example: "sort users.txt | uniq" },
  { name: "wc", category: "Texte", level: 3, description: "Compte les lignes, mots ou octets.", syntax: "wc [-lwc] [fichier]", example: "grep ERROR app.log | wc -l" },
  { name: "bash", category: "Scripts", level: 4, description: "Exécute des commandes ou un script Bash.", syntax: "bash script.sh", example: "bash scripts/backup.sh" },
  { name: "ssh", category: "Réseau", level: 4, description: "Ouvre une session distante chiffrée.", syntax: "ssh utilisateur@serveur", example: "ssh admin@server-lab" },
  { name: "scp", category: "Réseau", level: 4, description: "Copie des fichiers via SSH.", syntax: "scp source destination", example: "scp notes.txt admin@server:/tmp/" },
  { name: "ip", category: "Réseau", level: 4, description: "Affiche et configure le réseau.", syntax: "ip objet [action]", example: "ip addr" },
  { name: "ss", category: "Réseau", level: 4, description: "Affiche les sockets et ports.", syntax: "ss [options]", example: "ss -tuln" },
  { name: "curl", category: "Réseau", level: 4, description: "Transfère des données et teste des URL.", syntax: "curl [options] URL", example: "curl http://web.lab" },
  { name: "df", category: "Stockage", level: 4, description: "Affiche l'espace des systèmes de fichiers.", syntax: "df [-h]", example: "df -h" },
  { name: "du", category: "Stockage", level: 4, description: "Mesure la taille des fichiers et dossiers.", syntax: "du [-sh] chemin", example: "du -sh Projets" },
  { name: "journalctl", category: "Services", level: 4, description: "Consulte le journal systemd.", syntax: "journalctl [options]", example: "journalctl -u webapp" },
  { name: "systemctl", category: "Services", level: 4, description: "Contrôle les services systemd.", syntax: "systemctl action unité", example: "sudo systemctl restart webapp", danger: true },
  { name: "git", category: "Développement", level: 5, description: "Versionne le code et son historique.", syntax: "git action [options]", example: "git status" },
  { name: "docker", category: "Conteneurs", level: 5, description: "Gère images, conteneurs et applications Compose.", syntax: "docker action [options]", example: "docker compose ps", danger: true },
  { name: "ufw", category: "Sécurité", level: 5, description: "Gère simplement le pare-feu.", syntax: "ufw action", example: "sudo ufw status", danger: true },
];

export const GLOSSARY: GlossaryEntry[] = [
  { term: "Argument", definition: "Information transmise à une commande pour préciser sur quoi ou comment elle doit agir.", level: 1 },
  { term: "Commande", definition: "Instruction saisie dans le terminal puis exécutée par le shell.", level: 1 },
  { term: "Distribution", definition: "Ensemble composé du noyau Linux, de logiciels et d'outils de gestion.", level: 1 },
  { term: "Noyau", definition: "Partie centrale du système qui gère le matériel, la mémoire et les processus.", level: 1 },
  { term: "Prompt", definition: "Texte affiché par le shell pour indiquer qu'il attend une commande.", level: 1 },
  { term: "Shell", definition: "Programme qui interprète les commandes, comme Bash.", level: 1 },
  { term: "Chemin absolu", definition: "Chemin complet commençant à la racine /.", level: 2 },
  { term: "Chemin relatif", definition: "Chemin interprété à partir du dossier courant.", level: 2 },
  { term: "Racine", definition: "Sommet de l'arborescence Linux, représenté par /.", level: 2 },
  { term: "Permission", definition: "Règle déterminant qui peut lire, modifier ou exécuter un élément.", level: 3 },
  { term: "PID", definition: "Numéro unique attribué à un processus actif.", level: 3 },
  { term: "Pipe", definition: "Opérateur | qui transmet la sortie d'une commande à l'entrée d'une autre.", level: 3 },
  { term: "Processus", definition: "Instance d'un programme actuellement en cours d'exécution.", level: 3 },
  { term: "Variable d'environnement", definition: "Valeur nommée transmise aux programmes lancés depuis un shell.", level: 3 },
  { term: "Code de retour", definition: "Nombre indiquant si une commande s'est terminée correctement ; zéro signifie généralement réussite.", level: 4 },
  { term: "SSH", definition: "Protocole chiffré utilisé pour administrer et transférer des fichiers à distance.", level: 4 },
  { term: "Service", definition: "Programme fonctionnant en arrière-plan pour fournir une fonction durable.", level: 4 },
  { term: "Conteneur", definition: "Environnement isolé créé à partir d'une image et partageant le noyau de l'hôte.", level: 5 },
  { term: "Durcissement", definition: "Ensemble de mesures réduisant la surface d'attaque d'un système.", level: 5 },
  { term: "Incident", definition: "Événement qui perturbe ou menace un service et exige diagnostic, correction et vérification.", level: 5 },
];

export const totalCourseXp = ALL_LESSONS.reduce((sum, item) => sum + item.exercise.xp, 0) + COURSE_LEVELS.length * 150;
